### get all produk
GET http://localhost:5062/product
Content-Type: application/json

### post produk
POST http://localhost:5062/product
Content-Type: application/json

{
    "ProductName": "AOKA",
    "Price": 3000,
    "Stock": 50
}